### PR TITLE
Grammar fixes for Chapter 21 (continued), Part 6

### PR DESCRIPTION
**Pull request by LShun**
Hi, I fixed some grammar in some parts for Chapter 21 (continued), Part 6, will continue fixing it as time goes on, but for now, I would like to submit a pull request.

Thanks

### CODE REVIEW

**Comment by AgentMC** [comment]
@LShun Thanks for the contribution :) Maybe someday it will even become human-readable :)
Couple of hints for next PRs:

* Fine Reader had problem with certain characters, so there are certain words that are simply translated wrongly. Consider line 147, for example. It should not be 'rice', but 'US' (can you hear they sound similarly? I also can't so yeah, it's THAT bad). This specific case, I'll fix myself.
* Dazzl(ed | ing) = Mubling/murmuring/muttering, depending on the context
* Google translate AI tends to concatenate several sentences if it feels they are following the same subject. This results in ridiculously long sentences --> feel free to split.
* Parts of sentences separated by commas, or separate adjectives or gerunds can and should be rearranged to be applied to other nouns if it makes more sense.
* Should you any time feel "WTF does he mean?", consult corresponding line from RU translation which was revised with the source images. You can use same Google translate or Bing for that. Or ask me, I'll give a translation.

**Comment by AgentMC** [comment]
P.S.: oh yes, there's always Defan752 to consult with :)

**Comment by AgentMC** [comment]
P.P.S: the numbers (man-men) and pronouns (he-she) are messed up as there is a different sentence composition  and usage of pronouns in Japanese. Too bad I didn't know it when started the translation.

**Comment by LShun** [comment]
Ok, thanks, will keep those in mind. I don't really know Japanese, just making it more readable by fixing some of the "what?" moments.

**Pull request merged**
